[package]
name = "threefish512_app"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
zeroize = "1.6"
rand = "0.8"
fs2 = "0.4"
subtle = "2.5"
bincode = "1.3"

[dev-dependencies]
tempfile = "3"