[package]
name = "sps"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
chacha20poly1305 = "0.10"
rand = "0.8"
fs2 = "0.4"
log = "0.4"
env_logger = "0.10"
hex = "0.4"
zeroize = "1.8"